# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    echo "Installing dependencies..."
    npm ci

    echo "Running build..."
    npm run build

    echo "Checking for updates..."
    npm outdated

    echo "Updating packages..."
    npm update

    echo "Audit for vulnerabilities..."
    npm audit fix || echo "Non-fixable issues remain"

  displayName: 'Install, Build, and Update Packages'
